### PR TITLE
Initial support for NATS publisher

### PR DESCRIPTION
**Pull request by jarrodb**
This is a first iteration to add NATS support for publishing events.

The command line flag `-nats-server` was added to specify the server URL and `-dump` was modified to support a nats value.    Launching NATS from the command line looks like this:
```
./bin/gobmp -nats-server nats://localhost:4222 -dump nats
```

I verified the events were being generated with `nats stream info`:
```
State:

             Messages: 10,966
                Bytes: 10 MiB
             FirstSeq: 1 @ 2023-05-05T04:41:57 UTC
              LastSeq: 10,966 @ 2023-05-05T04:43:12 UTC
     Active Consumers: 0
   Number of Subjects: 6
```
and that the events were correct for each subject:
```
[10] Subject: gobmp.parsed.evpn Received: 2023-05-05T04:41:57Z

  Hash: 12de97c6ddc064947b35baadd1002bf9

{"action":"add","router_hash":"12de97c6ddc064947b35baadd1002bf9","router_ip": ... }
```

NATS terminology and implementation varies slightly from Kafka.  NATS uses `subjects` instead of `topics` and publishes messages to subjects.  I included the `key`, which equates to the router hash, in the header of the published message instead.

The acceptance criteria was a quick and simple implementation that worked and was backwards compatible, nothing more.

### CODE REVIEW

**Comment by jarrodb** [comment]
Related to #218

**Comment by sbezverk** [comment]
Thank you for PR, since I do not have NATS infra, it is hard for me to test nats publisher functionality. Could you please share some output frmo NATS side just to see the messages are getting in.

**Comment by jarrodb** [comment]
@sbezverk thank you for the response!  I'm carrying an image of my branch in a k8s deployment that is currently consuming BMP from our route reflectors and the events are correctly being published into their specific "topics" (NATS subjects).

From the `NATS output` in the previous comment, you can see over 10,000 messages received that are spread across the appropriate topics.  Here is a more recent breakdown that shows the `gobmp` stream receiving the messages (the RRs carry a lot of EVPN):

```
# nats stream subjects
? Select a Stream gobmp

            gobmp.parsed.ls_node:     13           gobmp.parsed.ls_link:     20
          gobmp.parsed.ls_prefix:     14        gobmp.parsed.statistics:    165
               gobmp.parsed.peer:     15              gobmp.parsed.evpn: 29,652
```

Here is a _redacted_ gobmp.parsed.peer:
```
{"action":"add","router_hash":"76e94565076d98cb3ced5700f208f775","remote_bgp_id":"10.80.151.1","router_ip":"145.40.84.38","timestamp":"2023-05-05T14:17:26Z","remote_asn":64XXX,"remote_ip":"172.16.X.X","peer_type":0,"peer_rd":"0:0","remote_port":64133,"local_asn":65XXX,"local_ip":"X.X.X.X","local_port":179,"local_bgp_id":"10.81.X.X","adv_cap":{"1":[{"capability_value":"ABkARg==","capability_descr":"Multiprotocol Extensions for BGP-4 : afi=25 safi=70 BGP EVPN "}],"128":[{"capability_descr":"Prestandard Route Refresh (deprecated)"}],"2":[{"capability_descr":"Route Refresh Capability for BGP-4"}],"64":[{"capability_value":"QHg=","capability_descr":"Graceful Restart Capability"}],"65":[{"capability_value":"AAD//A==","capability_descr":"Support for 4-octet AS number capability"}],"71":[{"capability_descr":"Long-Lived Graceful Restart (LLGR) Capability"}]},"recv_cap":{"1":[{"capability_value":"ABkARg==","capability_descr":"Multiprotocol Extensions for BGP-4 : afi=25 safi=70 BGP EVPN "}],"128":[{"capability_descr":"Prestandard Route Refresh (deprecated)"}],"2":[{"capability_descr":"Route Refresh Capability for BGP-4"}],"64":[{"capability_value":"QHg=","capability_descr":"Graceful Restart Capability"}],"65":[{"capability_value":"AAD8Jg==","capability_descr":"Support for 4-octet AS number capability"}],"71":[{"capability_descr":"Long-Lived Graceful Restart (LLGR) Capability"}]},"remote_holddown":90,"adv_holddown":90,"is_l":false,"is_prepolicy":false,"is_ipv4":true,"is_adj_rib_in_post_policy":false,"is_adj_rib_out_post_policy":false,"is_loc_rib_filtered":false}
```

Here is an example EVPN message:
```
{"action":"del","router_hash":"76e94565076d98cb3ced5700f208f775","router_ip":"X.X.X.X","base_attrs":{"base_attr_hash":"0ae0a8ba138a294ead0bb379a70171ae","is_atomic_agg":false},"peer_hash":"ac7bdbec0e7eeab6a6030df9f4534b34","remote_bgp_id":"10.80.X.X","peer_ip":"172.16.X.X","peer_type":0,"peer_asn":64XXX,"timestamp":"2023-05-06T00:48:16Z","is_ipv4":true,"is_nexthop_ipv4":true,"vpn_rd":"172.16.X.X:20473","vpn_rd_type":0,"eth_tag":"AAAAAA==","ip_address":"172.16.X.X","ip_len":32,"route_type":3,"is_adj_rib_in_post_policy":true,"is_adj_rib_out_post_policy":false,"is_loc_rib_filtered":false}
```

I plan on improving this publisher as I continue development, but so far it's working as expected and I'm generating key/values from the events in our data warehouse.

Let me know if you want me to do something more specific.

**Comment by jarrodb** [comment]
I had some free time so I created a test as a PR on my forked repository that you can view here: https://github.com/jarrodb/gobmp/pull/1

This PR introduces a simple test of the NATS publisher.  Before running the test, the following elements are created:

* in-memory NATS server 
* NATS connection for subscribing 
* NATS Publisher
* BMP Server

The test sends the bytes for a PeerStateChange to the BMP Server, which tests a production flow that parses the message and publishes the event.

Finally, the test subscribes to the gobmp topic/subject and compares a couple of attributes from the body (`Action` and `RouterHash`)

**Review by sbezverk — APPROVED** [review]

**Pull request merged**
