### PR TITLE
ext community refactor

### PR DESCRIPTION
**Pull request by sbezverk**
Signed-off-by: Serguei Bezverkhi <sbezverk@cisco.com>

This PR refactors Extended Community processing to make it more modular and extensible

### CODE REVIEW

**Comment by SergeKrier** [comment]
what's the point of using 3 letters acronym (sometimes cryptic), for the extended communities, can we use more human readable format ?

**Comment by sbezverk** [comment]
@SergeKrier I was trying to follow as much as I can existing conventions. I am ok to revise naming, we just need to make sure it will not break anything which is already using certain prefixes. @brmcdoug  Could you please check proposed changes and let me know if it will break anything on your side in topology code.

**Comment by brmcdoug** [comment]
I don't think the changes will break anything on the topology side. Most of those items are not yet in use, or like in the case of l3vpn, we already have "rt="

**Review by SergeKrier — APPROVED** [review]
I would have used ExCom prefix instead of EC but would be probably too long, ok like this

**Pull request merged**
